"""
custody_calculator.py - Compute day-by-day custody intervals.
Inputs: custody_rules.json + standard_calendar.json
Output: custody_intervals.json (array of {start, end, custodian, reason})

All rules derived from custody_rules.json (which comes from statute JSON).
No hard-coded assumptions.
"""
import json
import os
import sys
import calendar as calmod
from datetime import date, timedelta
from dataclasses import dataclass
from typing import Literal

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))


@dataclass
class Interval:
    start: date
    end: date
    custodian: Literal["dad", "mom"]
    reason: str

    def to_dict(self) -> dict:
        return {
            "start": str(self.start),
            "end": str(self.end),
            "custodian": self.custodian,
            "reason": self.reason,
        }


class CustodyCalculator:
    """
    Computes custody intervals for all school years.
    Reads rules from custody_rules.json (generated by rule_builder.py).
    Reads school calendar from standard_calendar.json.
    """

    def __init__(self, rules: dict, calendar_data: dict):
        self.rules = rules
        self.cal = calendar_data
        self.school_years = calendar_data.get("schoolYears", [])

    # ─── Static helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _nth_weekday(year: int, month: int, weekday: int, n: int) -> date:
        """Nth occurrence of weekday in month. weekday: 0=Mon, 6=Sun."""
        c = calmod.Calendar()
        occurrences = [day for day in c.itermonthdays2(year, month)
                       if day[0] != 0 and day[1] == weekday]
        if n - 1 < len(occurrences):
            return date(year, month, occurrences[n - 1][0])
        return None

    @staticmethod
    def _fathers_day(year: int) -> date:
        """Third Sunday of June."""
        return CustodyCalculator._nth_weekday(year, 6, 6, 3)

    @staticmethod
    def _mothers_day(year: int) -> date:
        """Second Sunday of May."""
        return CustodyCalculator._nth_weekday(year, 5, 6, 2)

    @staticmethod
    def _all_fridays(year: int, month: int) -> list:
        """All Fridays in the given month."""
        c = calmod.Calendar()
        return sorted([
            date(year, month, day[0])
            for day in c.itermonthdays2(year, month)
            if day[0] != 0 and day[1] == 4
        ])

    def _is_noschool_day(self, d: date) -> bool:
        """Return True if d is a no-school day for students.
        Checks both standalone noschool_days AND days within school breaks."""
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            sy_end = date.fromisoformat(sy["end"])
            if not (sy_start <= d <= sy_end):
                continue
            # Check standalone noschool days
            noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
            if d in noschool:
                return True
            # Check if d is inside a school break (students off during break)
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                br_end = date.fromisoformat(br["end"])
                if br_start <= d <= br_end:
                    return True
        return False

    # ─── Break detection ─────────────────────────────────────────────────────

    def _in_which_break(self, d: date) -> tuple:
        """
        Return (break_name, break_data) or (None, None).
        Checks ALL breaks in all school years regardless of the school year date range.
        Also handles pre-school summer gaps: May 22 through the day before
        each school year starts (Aug 13-17 for 2025-2026) - kids not yet in
        school, so treated as summer for custody purposes.
        """
        for sy in self.school_years:
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                br_end = date.fromisoformat(br["end"])
                if br_start <= d <= br_end:
                    # Map summer_pre_school to regular summer for custody purposes
                    effective_br_name = "summer" if br_name == "summer_pre_school" else br_name
                    return effective_br_name, br

        # Pre-school summer gap: May 22 through the day before school year starts.
        # Kids aren't in school yet = summer (mom).
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            # If school starts Aug or Sep, the pre-school summer is May 22-Aug (start-1).
            # This only applies within a single calendar year May-Aug window.
            if sy_start.month not in (8, 9):
                continue
            # effective_summer covers May 22 through (sy_start - 1 day)
            effective_summer_end = sy_start - timedelta(days=1)
            if effective_summer_end.month not in (7, 8):
                continue
            # Check: is d between May 22 and (sy_start - 1) of the calendar year
            # that sy_start falls in? If so, it's pre-school summer (mom).
            summer_start_of_year = date(sy_start.year, 5, 22)
            if not (summer_start_of_year <= d < sy_start):
                continue
            if "summer" in sy.get("breaks", {}):
                return "summer", sy["breaks"]["summer"]
            return "summer", {
                "start": summer_start_of_year.isoformat(),
                "end": effective_summer_end.isoformat()
            }

        return None, None

    def _break_custodian(
        self, break_name: str, break_data: dict, d: date, is_odd_year: bool
    ) -> tuple:
        """
        Determine custodian for a day within a break.
        """
        rules = self.rules
        br_start = date.fromisoformat(break_data["start"])

        if break_name == "thanksgiving":
            parent = rules["holidays"]["thanksgiving"]["odd_year" if is_odd_year else "even_year"]
            return parent, "thanksgiving"

        elif break_name == "christmas":
            split = date(br_start.year, 12, 28)
            is_first_half = d <= split
            if is_odd_year:
                parent = (rules["holidays"]["christmas"]["odd_year_first"] if is_first_half
                          else rules["holidays"]["christmas"]["odd_year_second"])
            else:
                parent = (rules["holidays"]["christmas"]["even_year_first"] if is_first_half
                          else rules["holidays"]["christmas"]["even_year_second"])
            reason = "christmas_first_half" if is_first_half else "christmas_second_half"
            return parent, reason

        elif break_name == "spring":
            parent = rules["holidays"]["spring_break"]["odd_year" if is_odd_year else "even_year"]
            return parent, "spring_break"

        elif break_name == "summer":
            # Dad gets July 1-30; all other summer days are mom
            dad_start = date(d.year, 7, 1)
            dad_end = date(d.year, 7, 30)
            if dad_start <= d <= dad_end:
                return rules["summer"]["possessory_parent"], "summer_possessory"
            else:
                return rules["summer"]["remainder_parent"], "summer_remainder"

        # Unknown break type → mom
        return rules["parents"]["managing"], break_name

    # ─── Main logic ──────────────────────────────────────────────────────────

    def _get_custodian(self, d: date) -> tuple:
        """
        Determine custodian for a single date.
        Priority order (per §153.314):
          1. Parents day - checked FIRST, overrides everything
          2. Last school day BEFORE a break = that break day 1
          3. School breaks (thanksgiving, christmas, spring, summer)
          4. Extended Weekend Rule: if Thu is dad's, Fri-Sat-Sun also belong to dad
          5. Regular school day Thu / 1st-3rd-5th Fri rules
          6. Fallback: managing conservator (mom)
        """
        rules = self.rules
        is_odd_year = d.year % 2 == 1

        # 1. Parents day
        fd = self._fathers_day(d.year)
        if fd:
            fri_before_fd = fd - timedelta(days=2)
            if fri_before_fd <= d <= fd:
                return rules["fathers_day"]["parent"], "fathers_day"

        md = self._mothers_day(d.year)
        if md:
            fri_before_md = md - timedelta(days=2)
            if fri_before_md <= d <= md:
                return rules["mothers_day"]["parent"], "mothers_day"

        # 2. Special: last school day BEFORE a break = that break day 1
        # Check each break; if d is the last school day before it starts, it's break day 1
        for sy in self.school_years:
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                # Walk backward from br_start-1 to find last school day
                prev = br_start - timedelta(days=1)
                for _ in range(90):
                    if prev.weekday() < 5:  # Mon-Fri
                        noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
                        if prev in noschool:
                            prev -= timedelta(days=1)
                            continue
                        # Not in another break?
                        in_other = any(
                            date.fromisoformat(b2["start"]) <= prev <= date.fromisoformat(b2["end"])
                            for n2, b2 in sy.get("breaks", {}).items()
                            if n2 != br_name
                        )
                        if not in_other:
                            break
                        prev -= timedelta(days=1)
                    else:
                        prev -= timedelta(days=1)
                else:
                    prev = br_start - timedelta(days=1)

                if d == prev:
                    # d is the last school day before this break - it's break day 1
                    br_data = {"start": br["start"], "end": br["end"], "label": br.get("label", {})}
                    return self._break_custodian(br_name, br_data, d, is_odd_year)

        # 3. School breaks (normal case)
        break_name, break_data = self._in_which_break(d)
        if break_name:
            return self._break_custodian(break_name, break_data, d, is_odd_year)

        # 4. Extended Weekend Rule (per §153.314(e))
        # Only applies on 1st/3rd/5th Fridays - the "weekend" belongs to dad,
        # and the Thu overnight extends to cover Fri-Sat-Sun as one block.
        if d.weekday() == 4:  # Friday
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    # This is a dad weekend — Thu overnight extends to cover it
                    return "dad", "weekend"

        if d.weekday() in (5, 6):  # Saturday or Sunday
            fri = d - timedelta(days=d.weekday() - 4)  # preceding Friday
            fridays = sorted(self._all_fridays(fri.year, fri.month))
            if fri in fridays:
                fri_rank = fridays.index(fri) + 1
                if fri_rank in [1, 3, 5]:
                    return "dad", "weekend"

        # 4b. Non-qualifying Friday no-school day (per §153.312)
        # If Thu was a school day (Dad's) and Fri is a no-school day,
        # "school dismissal Friday" never occurred — Dad's possession rolls forward.
        # Extended through the weekend until school resumes.
        if d.weekday() == 4:  # Friday no-school
            thu = d - timedelta(days=1)  # preceding Thursday
            thu_was_school = thu.weekday() == 3 and not self._is_noschool_day(thu)
            if thu_was_school:
                # Dad had Thu school day; Fri no-school — possession rolls forward
                return "dad", "no_school_day"

        # 4c. Weekend extension for Dad's no-school Friday
        # After a qualifying Fri no-school (step 4) OR non-qualifying Fri no-school (step 4b),
        # Sat-Sun-Mon belong to Dad until school resumes.
        if d.weekday() in (5, 6):  # Saturday or Sunday
            fri = d - timedelta(days=d.weekday() - 4)  # preceding Friday
            if self._is_noschool_day(fri):
                # Preceding Fri was a no-school day — Dad's possession extended
                return "dad", "no_school_day"

        # 4d. Monday no-school extends Dad's weekend
        # Per §153.312: if weekend coincides with a holiday (no-school Mon),
        # possession ends at 6 p.m. on the holiday.
        # If the preceding Fri was a qualifying dad weekend (step 4),
        # and Mon is no-school, Dad extends through Mon.
        if d.weekday() == 0:  # Monday
            fri = d - timedelta(days=3)  # preceding Friday
            fridays = sorted(self._all_fridays(fri.year, fri.month))
            if fri in fridays:
                fri_rank = fridays.index(fri) + 1
                was_dad_weekend = fri_rank in [1, 3, 5]
            else:
                was_dad_weekend = False
            was_noschool_fri = self._is_noschool_day(fri)
            if (was_dad_weekend or was_noschool_fri) and self._is_noschool_day(d):
                # Dad's weekend extends through Mon no-school day
                return "dad", "no_school_day"

        # 5. Regular school day rules: Thursday + 1st-3rd-5th Friday
        if d.weekday() == 3:  # Thursday
            return rules["thursday"]["parent"], "thursday"

        if d.weekday() == 4:  # Friday
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    return rules["weekend"]["parent"], "weekend"

        # 6. Fallback: managing conservator (mom)
        return rules["parents"]["managing"], "default_custody"

    def _no_extended_weekend(self, d: date) -> tuple:
        """
        Internal custodian check that does NOT apply the extended weekend rule.
        Used only by the extended weekend check to avoid infinite recursion.
        """
        rules = self.rules
        is_odd_year = d.year % 2 == 1
        fd = self._fathers_day(d.year)
        if fd:
            fri_before_fd = fd - timedelta(days=2)
            if fri_before_fd <= d <= fd:
                return rules["fathers_day"]["parent"], "fathers_day"
        md = self._mothers_day(d.year)
        if md:
            fri_before_md = md - timedelta(days=2)
            if fri_before_md <= d <= md:
                return rules["mothers_day"]["parent"], "mothers_day"
        break_name, break_data = self._in_which_break(d)
        if break_name:
            return self._break_custodian(break_name, break_data, d, is_odd_year)
        if d.weekday() == 3:
            return rules["thursday"]["parent"], "thursday"
        if d.weekday() == 4:
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    return rules["weekend"]["parent"], "weekend"
        return rules["parents"]["managing"], "default_custody"

        """
        Internal custodian check that does NOT apply the extended weekend rule.
        Used only by the extended weekend check to avoid infinite recursion.
        """
        rules = self.rules
        is_odd_year = d.year % 2 == 1
        fd = self._fathers_day(d.year)
        if fd:
            fri_before_fd = fd - timedelta(days=2)
            if fri_before_fd <= d <= fd:
                return rules["fathers_day"]["parent"], "fathers_day"
        md = self._mothers_day(d.year)
        if md:
            fri_before_md = md - timedelta(days=2)
            if fri_before_md <= d <= md:
                return rules["mothers_day"]["parent"], "mothers_day"
        break_name, break_data = self._in_which_break(d)
        if break_name:
            return self._break_custodian(break_name, break_data, d, is_odd_year)
        if d.weekday() == 3:
            return rules["thursday"]["parent"], "thursday"
        if d.weekday() == 4:
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    return rules["weekend"]["parent"], "weekend"
        return rules["parents"]["managing"], "default_custody"

    def _last_school_day_before_break(self, break_name: str):
        """
        Return the last actual school day BEFORE a break starts.
        This day belongs to the break, not to regular custody.
        e.g. Dec 18 (last day before Christmas) = Christmas day 1
             May 21 (last day before summer) = summer day 1
        """
        for sy in self.school_years:
            br = sy.get("breaks", {}).get(break_name)
            if not br:
                continue
            br_start = date.fromisoformat(br["start"])
            noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
            prev = br_start - timedelta(days=1)
            for _ in range(90):
                if prev.weekday() < 5 and prev not in noschool:
                    in_other = any(
                        s <= prev <= e
                        for name, b in sy.get("breaks", {}).items()
                        if name != break_name
                        for s, e in [(date.fromisoformat(b["start"]), date.fromisoformat(b["end"]))]
                    )
                    if not in_other:
                        return prev
                prev -= timedelta(days=1)
            return None
        return None


    # ─── Compute all intervals ───────────────────────────────────────────────

    def compute_intervals(self) -> list:
        """
        Compute custody intervals for ALL calendar days from earliest school year
        start through latest school year end. This ensures summer breaks between
        and across school years are fully covered.
        """
        all_starts = sorted({date.fromisoformat(sy["start"]) for sy in self.school_years})
        all_ends = sorted({date.fromisoformat(sy["end"]) for sy in self.school_years})
        if not all_starts:
            return []

        intervals = []
        # Start from May 22 two years before to capture pre-instruction gap days
        first_sy_start = all_starts[0]
        d = date(first_sy_start.year - 2, 5, 22)
        end_d = all_ends[-1]

        while d <= end_d:
            custodian, reason = self._get_custodian(d)
            if intervals and intervals[-1].custodian == custodian and intervals[-1].reason == reason:
                intervals[-1].end = d
            else:
                intervals.append(Interval(d, d, custodian, reason))
            d += timedelta(days=1)

        return intervals

    def save_intervals(self, intervals: list, output_path: str) -> None:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(
                {"count": len(intervals), "intervals": [iv.to_dict() for iv in intervals]},
                f, indent=2, ensure_ascii=False
            )
        print(f"[custody_calculator] Saved {len(intervals)} intervals to {output_path}")


def load_rules(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_standard_calendar(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    rules = load_rules(sys.argv[1])
    cal = load_standard_calendar(sys.argv[2])
    calc = CustodyCalculator(rules, cal)
    intervals = calc.compute_intervals()
    checks = [
        ("2025-08-13", "pre-school summer", "mom", "regular_school_day"),
        ("2025-09-05", "1st Friday Sep", "dad", "weekend"),
        ("2025-09-06", "Saturday", "mom", "regular_school_day"),
        ("2025-11-24", "thanksgiving odd Dad", "dad", "thanksgiving"),
        ("2025-11-28", "thanksgiving odd Dad", "dad", "thanksgiving"),
        ("2025-12-19", "christmas first odd", "dad", "christmas_first_half"),
        ("2025-12-29", "christmas second odd", "mom", "christmas_second_half"),
        ("2026-03-16", "spring break even", "dad", "spring_break"),
        ("2026-07-15", "summer Dad days", "dad", "summer_possessory"),
        ("2026-08-12", "summer remainder", "mom", "summer_remainder"),
        ("2026-06-19", "fathers day weekend", "dad", "regular_school_day"),
        ("2026-06-20", "fathers day weekend", "dad", "regular_school_day"),
        ("2026-06-21", "fathers day", "dad", "regular_school_day"),
        ("2026-05-10", "mothers day", "mom", "regular_school_day"),
    ]
    print(f"Total intervals: {len(intervals)}")
    for ds, desc, exp_c, exp_r in checks:
        d = date.fromisoformat(ds)
        for iv in intervals:
            if iv.start <= d <= iv.end:
                ok = "OK" if iv.custodian == exp_c and iv.reason == exp_r else "FAIL"
                print(f"  {ds} {desc[:20]:20s}: {iv.custodian} ({iv.reason}) [{ok}]")
                break
